Introduce NGXS
Calciumdibromid/CaBr2 pull request #1048
Opened 2022-01-20 21:07 UTC by Epsilon02

close #848

2022-01-27 19:58 UTC, Epsilon02 commented
For some reference: https://www.ngxs.io/concepts/intro

2022-01-28 04:21 UTC, crapStone commented on frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.scss
> +  font-size: 1.1em !important;
@6543 should we let this through or does he need to open a new PR?

2022-01-28 07:11 UTC, Epsilon02 commented on frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.scss
> +  font-size: 1.1em !important;
This was needed to get the same icon alignment as before, because there is now a child component in this component.
If i leave this out there, the fix of https://github.com/Calciumdibromid/CaBr2/pull/1006 in `src/app/components/modifiable-string-list/modifiable-string-list.component.html` is gone. (Weird Angular Material behavior in this case, that I need another way to get nearly the same behavior than before.)

2022-01-28 19:07 UTC, crapStone requested changes

2022-01-28 19:07 UTC, crapStone commented on frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.ts
> +  add = new EventEmitter();
```suggestion
  addEmpty = new EventEmitter();
```

2022-01-28 19:07 UTC, crapStone commented on frontend/src/app/components/modifiable-string-list/modifiable-string-list.component.ts
>      this.controlElements.removeAt(index);
is this line still needed?

2022-01-28 19:15 UTC, crapStone commented on frontend/src/app/@core/actions/disposal.actions.ts
> +  static readonly type = '[Disposal] add sentence';
or `empty`

2022-01-29 15:06 UTC, Epsilon02 commented on frontend/src/app/@core/operators/string-list-operators.ts
> +    const elements = state.form.model?.elements.slice();
The `state` and their children are, because of the ngxs state behavior, readonly, but I need to modify the array.
NGXS uses nearly the same logic in their [example](https://www.ngxs.io/concepts/state#actions-with-a-payload).
(I am not entirely sure but I think there is no difference between `array.slice()` and `[...array]`)

2022-01-29 17:24 UTC, crapStone approved these changes

2022-01-30 00:10 UTC, 6543 approved these changes

2022-01-30 00:11 UTC, merged