replace config-model hack with ngxs approach
Calciumdibromid/CaBr2 pull request #1111
Opened 2022-02-01 20:33 UTC by Epsilon02

close #1092

2022-02-01 23:59 UTC, crapStone requested changes
The settings dialog state is not consistent, but I have to investigate more.

2022-02-01 23:59 UTC, crapStone commented on frontend/src/app/@core/services/config/web/config.service.ts
> +    throw Error('Loadconfig is for web not required');
... not required for web

2022-02-01 23:59 UTC, crapStone commented on frontend/src/app/@core/services/config/web/config.service.ts
> +    throw Error('Saveconfig is for web not required');
here too

2022-02-02 10:17 UTC, Epsilon02 commented
> The settings dialog state is not consistent, but I have to investigate more.

Hm please try it in a incognito window maybe there is a problem with the localstorage :thinking: 
I'm not sure I had this issue too, because I cleared my localstorage during testing.

2022-02-02 13:48 UTC, crapStone approved these changes

2022-02-02 14:01 UTC, merged