Add Save to PDF
Calciumdibromid/CaBr2 pull request #120
Opened 2021-02-14 20:28 UTC by 6543

close #89

2021-02-14 22:38 UTC, 6543 commented on src-tauri/src/load_save/pdf/mod.rs
> +}
```
13 | / lazy_static! {
14 | |   static ref pdf_app: Arc<Mutex<PdfApplication>> =
15 | |     Arc::new(Mutex::new(PdfApplication::new().expect("cant initialice wkhtmltopdf")));
16 | | }
   | |_^ `*const ()` cannot be sent between threads safely
```
cc @crapStone

2021-02-16 15:40 UTC, crapStone commented
https://lib.rs/crates/lopdf

2021-02-17 22:31 UTC, crapStone requested changes

2021-02-17 22:31 UTC, crapStone commented on src-tauri/src/load_save/pdf/mod.rs
> +  let mut program_path = program_path.parent().unwrap().to_path_buf();
```suggestion
  // TODO make path os independent
  let mut program_path = program_path.parent().unwrap().to_path_buf();
```

2021-02-17 22:32 UTC, Epsilon02 approved these changes

2021-02-17 22:32 UTC, crapStone approved these changes

2021-02-17 22:51 UTC, merged