WIP: Move Strings to json
Calciumdibromid/CaBr2 pull request #155
Opened 2021-02-17 02:21 UTC by 6543

move strings from template to json

2021-02-18 11:15 UTC, 6543 commented
one question: should we just use 1 "strings.json" ?

2021-02-18 11:19 UTC, 6543 commented on src/strings/header.json
> +        "org": "Organisation:",
organisation

2021-03-06 11:58 UTC, Epsilon02 reviewed
Some refactorings in HTMLs are in my opinion less readable.
I marked a few but not all.
Was this refactoring done by Prettier?

2021-03-06 11:58 UTC, Epsilon02 commented on src/app/search/edit-search-results/edit-search-results.component.html
> +            matTooltipPosition="right">
Was this refactoring by Prettier?
For me it is less readable than before

2021-03-06 11:58 UTC, Epsilon02 commented on src/app/search/edit-search-results/edit-search-results.component.html
> +            alt="{{ key }}" />
It is less readable than before

2021-03-06 11:58 UTC, Epsilon02 commented on src/app/search/edit-search-results/edit-search-results.component.html
> +                matTooltipPosition="left">
Less readable than before

2021-03-06 18:52 UTC, 6543 commented on src/app/search/edit-search-results/edit-search-results.component.html
> +            matTooltipPosition="right">
> refactoring by Prettier

yes ... we need to make sure Prettier works on all systems as expected

2021-03-06 19:13 UTC, crapStone requested changes

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +        <mat-error *ngIf="this.form.get('name')?.get('value')?.invalid">{{ strings.substance.needName }}</mat-error>
```suggestion
        <mat-error *ngIf="this.form.get('name')?.get('value')?.invalid">{{ strings.substance.needsName }}</mat-error>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +          <mat-error *ngIf="this.form.get('amount')?.get('value')?.invalid">{{ strings.substance.noNumber }}</mat-error>
```suggestion
          <mat-error *ngIf="this.form.get('amount')?.get('value')?.invalid">{{ strings.substance.notANumber }}</mat-error>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +          <mat-label>{{ strings.substance.ownUnit }}</mat-label>
```suggestion
          <mat-label>{{ strings.substance.customUnit }}</mat-label>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +                [matTooltip]="strings.substance.rmHPhrase"
```suggestion
                [matTooltip]="strings.substance.removeHPhrase"
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +                [matTooltip]="strings.substance.rmPPhrase"
```suggestion
                [matTooltip]="strings.substance.removePPhrase"
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +      <p>{{ strings.substance.ghsSymbolsAddRmInfo }}</p>
```suggestion
      <p>{{ strings.substance.ghsSymbolsAddOrRemoveInfo }}</p>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/edit-search-results/edit-search-results.component.html
> +    <button mat-button (click)="close()">{{ strings.base.cancle }}</button>
```suggestion
    <button mat-button (click)="close()">{{ strings.base.cancel }}</button>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search-dialog/search-dialog.component.html
> +<h2>{{ strings.search.resultHeader }}</h2>
```suggestion
<h2>{{ strings.search.resultsHeader }}</h2>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search-dialog/search-dialog.component.html
> +  <button mat-button (click)="close(true)">{{ strings.base.cancle }}</button>
```suggestion
  <button mat-button (click)="close(true)">{{ strings.base.cancel }}</button>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search-dialog/search-dialog.component.ts
> +        this.alertService.error(strings.error.loadSearchResult);
```suggestion
        this.alertService.error(strings.error.loadSearchResults);
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search.component.html
> +  <button class="button unselectable" mat-flat-button color="primary" (click)="openDialog()">{{ strings.search.search }}</button>
```suggestion
  <button class="button unselectable" mat-flat-button color="primary" (click)="openDialog()">{{ strings.search.searchButton }}</button>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search.component.html
> +        <mat-header-cell *matHeaderCellDef> {{ strings.substance.casNr }}</mat-header-cell>
```suggestion
        <mat-header-cell *matHeaderCellDef> {{ strings.substance.casNumber }}</mat-header-cell>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search.component.html
> +              [matTooltip]="strings.search.rmSubstance"
```suggestion
              [matTooltip]="strings.search.removeSubstance"
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/selected-search/selected-search.component.html
> +          <mat-label>{{strings.search.option}}</mat-label>
```suggestion
          <mat-label>{{ strings.search.option }}</mat-label>
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/selected-search/selected-search.component.html
> +              [matTooltip]="strings.search.rmOption"
```suggestion
              [matTooltip]="strings.search.removeOption"
```

2021-03-06 19:13 UTC, crapStone commented on src/app/search/search.component.ts
> +              this.alertService.error(strings.error.substanceWithCASSExist);
```suggestion
              this.alertService.error(strings.error.substanceWithCASExist);
```

2021-03-06 19:13 UTC, crapStone commented on src/app/preview/preview.component.html
> +          {{ strings.descriptions.signStudent }}
```suggestion
          {{ strings.descriptions.signatureFieldStudent }}
```

2021-03-06 19:13 UTC, crapStone commented on src/app/preview/preview.component.html
> +          {{ strings.descriptions.signAssistant }}
```suggestion
          {{ strings.descriptions.signatureFieldAssistant }}
```

2021-03-06 19:21 UTC, crapStone requested changes

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "cancle": "Abbrechen",
```suggestion
      "cancel": "Abbrechen",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "needName": "Name benötigt",
```suggestion
      "needsName": "Name benötigt",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "noNumber": "Keine Zahl",
```suggestion
      "notANumber": "Keine Zahl",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "ownUnit": "Eigene Einheit",
```suggestion
      "customUnit": "Eigene Einheit",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "rmHPhrase": "P-Satz entfernen",
```suggestion
      "removeHPhrase": "P-Satz entfernen",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "rmPPhrase": "P-Satz entfernen",
```suggestion
      "removePPhrase": "P-Satz entfernen",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "ghsSymbolsAddRmInfo": "Zum entfernen oder hinzufügen auf das Symbol klicken",
```suggestion
      "ghsSymbolsAddOrRemoveInfo": "Zum entfernen oder hinzufügen auf das Symbol klicken",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "resultHeader": "Suchergebnisse",
```suggestion
      "resultsHeader": "Suchergebnisse",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "loadSearchResult": "Laden der Suchergebnisse fehlgeschlagen!",
```suggestion
      "loadSearchResults": "Laden der Suchergebnisse fehlgeschlagen!",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "search": "Suche",
```suggestion
      "searchButton": "Suche",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "casNr": "CAS Nummer",
```suggestion
      "casNumber": "CAS Nummer",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "rmSubstance": "Substanz entfernen",
```suggestion
      "removeSubstance": "Substanz entfernen",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "rmOption": "Suchoption entfernen",
```suggestion
      "removeOption": "Suchoption entfernen",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "substanceWithCASSExist": "Substanz mit selber CAS Nummer existiert bereits!",
```suggestion
      "substanceWithCASExist": "Substanz mit selber CAS Nummer existiert bereits!",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "signStudent": "Hiermit verpflichte ich mich, den Versuch gemäß den in dieser Betriebsanweisung aufgeführten Sicherheitsvorschriften durchzuführen.",
```suggestion
      "signatureFieldStudent": "Hiermit verpflichte ich mich, den Versuch gemäß den in dieser Betriebsanweisung aufgeführten Sicherheitsvorschriften durchzuführen.",
```

2021-03-06 19:21 UTC, crapStone commented on src/assets/strings.json
> +      "signAssistant": "Präparat zur Synthese mit den auf der Vorderseite berechneten Chemikalienmengen freigegeben."
```suggestion
      "signatureFieldAssistant": "Präparat zur Synthese mit den auf der Vorderseite berechneten Chemikalienmengen freigegeben."
```

2021-03-06 19:25 UTC, crapStone approved these changes

2021-03-06 20:11 UTC, merged