Feature/alert snackbar
Calciumdibromid/CaBr2 pull request #177
Opened 2021-02-20 17:47 UTC by Epsilon02

2021-02-20 17:50 UTC, 6543 commented
needed for #150

2021-02-21 01:11 UTC, crapStone requested changes

2021-02-21 01:11 UTC, crapStone commented on src/app/alertsnackbar/alertsnackbar.component.ts
> +        return;
raise an Error instead

2021-02-21 01:11 UTC, crapStone commented on src/app/alertsnackbar/alertsnackbar.component.ts
> +        setTimeout(() => this.removeAlert(alert), 3000);
```suggestion
        // TODO cleanup
        setTimeout(() => this.removeAlert(alert), 3000);
```

2021-02-21 02:56 UTC, crapStone approved these changes

2021-02-21 02:56 UTC, merged