Add Contribution Guidelines
Calciumdibromid/CaBr2 pull request #456
Opened 2021-04-29 07:18 UTC by 6543

close #122

2021-04-29 10:00 UTC, crapStone requested changes

2021-04-29 10:00 UTC, crapStone commented on CONTRIBUTING.md
> +Imports are sorted, src contain frontend only, src-tauri contain backend only.
we should specify this part more

2021-04-29 10:00 UTC, crapStone commented on CONTRIBUTING.md
> +We use semantic versioning.
```suggestion
We use [semantic](https://semver.org/) versioning.
```

2021-04-29 11:02 UTC, 6543 commented on CONTRIBUTING.md
> +Imports are sorted, src contain frontend only, src-tauri contain backend only.
Suggestions are welcome ;)

2021-05-02 17:51 UTC, crapStone requested changes

2021-05-02 17:51 UTC, crapStone commented on CONTRIBUTING.md
> +Imports are sorted, src contain frontend only, src-tauri contain backend only.
```suggestion
## Frontend/Angular

- all frontend-related code is in `src` folder
- imports should be arranged like this with empty lines in between:
  1. external libraries/browser builtins
  2. own modules
- imports should be sorted alphabetically
- use style defined in prettierrc:
  - always use trailing commas
  - use singlequotes
  - use 2 spaces to indent code
  - ...

## Backend/Rust

- all backend-ralated code is in `src-tauri`
- imports should be arranged like this with empty lines in between:
  1. standard library (`std`)
  2. external librarys
  3. internal libraries (prefixed with `cabr2_`)
  4. intra-library imports
- use style defined in `rustfmt.toml`:
  - always use trailing commas
  - use 2 spaces to indent code
  - ...
```

2021-05-02 17:52 UTC, crapStone commented on CONTRIBUTING.md
> +Imports are sorted, src contain frontend only, src-tauri contain backend only.
@Epsilon02 something to add?

2021-05-02 18:30 UTC, 6543 commented on CONTRIBUTING.md
> +
```suggestion
```

2021-05-02 18:31 UTC, 6543 commented on CONTRIBUTING.md
> +  - ...
@Epsilon02 something to add?

2021-05-02 19:32 UTC, Epsilon02 commented on CONTRIBUTING.md
> +Imports are sorted, src contain frontend only, src-tauri contain backend only.
Lgtm

2021-05-02 19:32 UTC, Epsilon02 commented on CONTRIBUTING.md
> +  - ...
Lgtm

2021-05-02 19:33 UTC, 6543 commented on CONTRIBUTING.md
> +  - ...
@Epsilon02 I think you have to use the review function :D

2021-05-02 19:34 UTC, Epsilon02 approved these changes

2021-05-02 19:56 UTC, crapStone approved these changes

2021-05-02 19:58 UTC, merged