added export and save buttons below preview
Calciumdibromid/CaBr2 pull request #486
Opened 2021-05-09 15:39 UTC by Epsilon02

close #463

2021-05-10 21:53 UTC, crapStone requested changes

2021-05-10 21:53 UTC, crapStone commented on src/app/menubar/menubar.component.html
> +        (click)="exportFile({ name: 'CaBr2', extensions: ['cb2'] })"
duplicated code!

should we create an extra function or a mapping from which these object can be pulled?

2021-05-11 16:36 UTC, crapStone requested changes

2021-05-11 16:36 UTC, crapStone commented on src/app/menubar/menubar.component.html
> +      <button mat-menu-item (click)="exportCab2File()">
```suggestion
      <button mat-menu-item (click)="exportCB2File()">
```

2021-05-13 00:57 UTC, 6543 commented on src/app/menubar/menubar.component.ts
> +  exportCab2File(): void {
```suggestion
  exportCB2File(): void {
```

2021-05-13 00:58 UTC, 6543 commented on src/app/menubar/menubar.component.html
> +        (click)="exportCab2File()"
```suggestion
        (click)="exportCB2File()"
```

2021-05-13 01:26 UTC, 6543 commented
this will ad those buttons, but can we put them to at the center or to the right side?

2021-05-13 12:30 UTC, Epsilon02 commented
I'm not sure if it make sense. I think the user have the cursor more on the left side because the most user interactions are on the left side to. Correct me if I'm wrong.

2021-05-13 14:34 UTC, 6543 approved these changes

2021-05-13 14:38 UTC, merged