moved image sanitizing to global model
Calciumdibromid/CaBr2 pull request #516
Opened 2021-05-13 16:46 UTC by Epsilon02

close #297

2021-05-13 23:20 UTC, crapStone requested changes

2021-05-13 23:20 UTC, crapStone commented on src/app/@core/models/global.model.ts
> +  private sanitizeImage(value: string): SafeResourceUrl {
remove this function

2021-05-14 19:25 UTC, Epsilon02 commented
lgtm

2021-05-14 19:32 UTC, crapStone approved these changes

2021-05-14 19:42 UTC, merged