drag and drop feature to change order of the second sheet
Calciumdibromid/CaBr2 pull request #543
Opened 2021-05-17 12:20 UTC by Epsilon02

2021-05-17 16:30 UTC, Epsilon02 commented
blocked by #544 cause of material angular syntax change.

2021-07-02 07:44 UTC, crapStone commented
Preview isn't updated immediately. You have to click in one of the text fields to trigger the update manually.

2021-07-02 07:45 UTC, crapStone requested changes
Preview isn't updated immediately. You have to click in one of the text fields to trigger the update manually.

2021-07-12 16:43 UTC, crapStone approved these changes

2021-07-12 16:43 UTC, merged