Feature/reolace selfmade localization with transloco
Calciumdibromid/CaBr2 pull request #801
Opened 2021-09-12 19:58 UTC by Epsilon02

2021-09-12 20:11 UTC, crapStone requested changes

2021-09-12 20:11 UTC, crapStone commented on src/app/@core/services/i18n/i18n.interface.ts
> +export interface AvailableLang {
```suggestion
export interface AvailableLanguage {
```

2021-09-12 20:11 UTC, crapStone commented on transloco.config.js
> +};
```suggestion
};

```

2021-09-12 21:10 UTC, crapStone approved these changes

2021-09-12 21:11 UTC, merged

2021-09-13 00:17 UTC, 6543 reviewed
changes in contrib/pull-translations missed